packages:
  - packages/**
  - docs
  - demo/*
  - e2e/**
  - test

catalog:
  '@better-fetch/fetch': 1.1.21
  better-call: 1.1.7
  tsdown: ^0.17.2
  typescript: ^5.9.3

catalogs:
  react19:
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    react: ^19.2.3
    react-dom: ^19.2.3
  vitest:
    '@vitest/coverage-v8': ^4.0.15
    vitest: ^4.0.15

neverBuiltDependencies: []
