packages:
  - packages/**
  - docs
  - demo/*
  - e2e/**
  - test

catalog:
  '@better-fetch/fetch': 1.1.18
  better-call: 1.1.4
  tsdown: ^0.16.0
  typescript: ^5.9.3

catalogs:
  vitest:
    vitest: ^4.0.14
    '@vitest/coverage-v8': ^4.0.14

  react19:
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    react: ^19.2.1
    react-dom: ^19.2.1

neverBuiltDependencies: []
