packages:
  - packages/**
  - docs
  - demo/*
  - e2e/**

catalog:
  '@better-fetch/fetch': 1.1.18
  better-call: 1.0.24
  tsdown: ^0.15.12
  typescript: ^5.9.3
  vitest: ^3.2.4

catalogs:
  react18:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    react: 19.2.0
    react-dom: 19.2.0

neverBuiltDependencies: []

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  miniflare>zod: ^3.25.1
  zod: ^4.1.5
