packages:
  - packages/**
  - dev/**
  - docs
  - examples/**
  - demo/*
catalogs:
  react18:
    '@types/react': ^18.3.14
    '@types/react-dom': ^18.3.2
    react: 18.3.1
    react-dom: 18.3.1
catalog:
  "better-call": "^1.0.3"
  "@better-fetch/fetch": "^1.1.15"
  "unbuild": "^3.5.0"
  "typescript": "^5.7.3"