packages:
  - packages/**
  - dev/**
  - docs
  - examples/**
  - demo/*
catalogs:
  react18:
    '@types/react': ^19.1.0
    '@types/react-dom': ^19.1.0
    react: 19.1.0
    react-dom: 19.1.0
catalog:
  "better-call": "^1.0.8"
  "@better-fetch/fetch": "^1.1.18"
  "unbuild": "^3.5.0"
  "typescript": "^5.7.3"