packages:
  - packages/**
  - docs
  - demo/*
  - e2e/**
  - test

catalog:
  '@better-fetch/fetch': 1.1.18
  better-call: 1.1.0
  tsdown: ^0.16.6
  typescript: ^5.9.3

catalogs:
  vitest:
    vitest: ^4.0.14
    '@vitest/coverage-v8': ^4.0.14

  react18:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

neverBuiltDependencies: []

patchedDependencies:
  msw: patches/msw.patch
