packages:
  - packages/**
  - docs
  - demo/*
  - e2e/**
  - test

catalog:
  '@better-fetch/fetch': 1.1.18
  better-call: 1.1.3
  tsdown: ^0.16.8
  typescript: ^5.9.3
  vitest: 4.0.14

catalogs:
  react18:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: 19.2.0
    react-dom: 19.2.0

neverBuiltDependencies: []

patchedDependencies:
  msw: patches/msw.patch
