packages:
  - packages/**
  - docs
  - demo/*
  - e2e/**

catalog:
  '@better-fetch/fetch': ^1.1.18
  better-call: 1.0.18
  typescript: ^5.9.2
  unbuild: ^3.6.1
  vitest: ^3.2.4

catalogs:
  react18:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

neverBuiltDependencies: []

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  miniflare>zod: ^3.25.1
  zod: ^4.1.5
