import { defineErrorCodes } from "../utils/error-codes";

export const BASE_ERROR_CODES = defineErrorCodes({
	ERR_USER_NOT_FOUND: "User not found",
	ERR_FAILED_TO_CREATE_USER: "Failed to create user",
	ERR_FAILED_TO_CREATE_SESSION: "Failed to create session",
	ERR_FAILED_TO_UPDATE_USER: "Failed to update user",
	ERR_FAILED_TO_GET_SESSION: "Failed to get session",
	ERR_INVALID_PASSWORD: "Invalid password",
	ERR_INVALID_EMAIL: "Invalid email",
	ERR_INVALID_EMAIL_OR_PASSWORD: "Invalid email or password",
	ERR_INVALID_USER: "Invalid user",
	ERR_SOCIAL_ACCOUNT_ALREADY_LINKED: "Social account already linked",
	ERR_PROVIDER_NOT_FOUND: "Provider not found",
	ERR_INVALID_TOKEN: "Invalid token",
	ERR_TOKEN_EXPIRED: "Token expired",
	ERR_ID_TOKEN_NOT_SUPPORTED: "id_token not supported",
	ERR_FAILED_TO_GET_USER_INFO: "Failed to get user info",
	ERR_USER_EMAIL_NOT_FOUND: "User email not found",
	ERR_EMAIL_NOT_VERIFIED: "Email not verified",
	ERR_PASSWORD_TOO_SHORT: "Password too short",
	ERR_PASSWORD_TOO_LONG: "Password too long",
	ERR_USER_ALREADY_EXISTS: "User already exists.",
	ERR_USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL:
		"User already exists. Use another email.",
	ERR_EMAIL_CAN_NOT_BE_UPDATED: "Email can not be updated",
	ERR_CREDENTIAL_ACCOUNT_NOT_FOUND: "Credential account not found",
	ERR_SESSION_EXPIRED: "Session expired. Re-authenticate to perform this action.",
	ERR_FAILED_TO_UNLINK_LAST_ACCOUNT: "You can't unlink your last account",
	ERR_ACCOUNT_NOT_FOUND: "Account not found",
	ERR_USER_ALREADY_HAS_PASSWORD:
		"User already has a password. Provide that to delete the account.",
	ERR_CROSS_SITE_NAVIGATION_LOGIN_BLOCKED:
		"Cross-site navigation login blocked. This request appears to be a CSRF attack.",
	ERR_VERIFICATION_EMAIL_NOT_ENABLED: "Verification email isn't enabled",
	ERR_EMAIL_ALREADY_VERIFIED: "Email is already verified",
	ERR_EMAIL_MISMATCH: "Email mismatch",
	ERR_SESSION_NOT_FRESH: "Session is not fresh",
	ERR_LINKED_ACCOUNT_ALREADY_EXISTS: "Linked account already exists",
	ERR_INVALID_ORIGIN: "Invalid origin",
	ERR_INVALID_CALLBACK_URL: "Invalid callbackURL",
	ERR_INVALID_REDIRECT_URL: "Invalid redirectURL",
	ERR_INVALID_ERROR_CALLBACK_URL: "Invalid errorCallbackURL",
	ERR_INVALID_NEW_USER_CALLBACK_URL: "Invalid newUserCallbackURL",
	ERR_MISSING_OR_NULL_ORIGIN: "Missing or null Origin",
	ERR_CALLBACK_URL_REQUIRED: "callbackURL is required",
	ERR_FAILED_TO_CREATE_VERIFICATION: "Unable to create verification",
	ERR_FIELD_NOT_ALLOWED: "Field not allowed to be set",
	ERR_ASYNC_VALIDATION_NOT_SUPPORTED: "Async validation is not supported",
	ERR_VALIDATION_ERROR: "Validation Error",
	ERR_MISSING_FIELD: "Field is required",
	ERR_METHOD_NOT_ALLOWED_DEFER_SESSION_REQUIRED:
		"POST method requires deferSessionRefresh to be enabled in session config",
});

export type APIErrorCode = keyof typeof BASE_ERROR_CODES;
