import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const genericOAuthPluginConfig = {
	displayName: "Generic OAuth",
	auth: {
		function: "genericOAuth",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "genericOAuth" })],
				isNamedImport: false,
			},
		],
	},
	authClient: {
		function: "genericOAuthClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "genericOAuthClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
