import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const haveIBeenPwnedPluginConfig = {
	displayName: "Have IBeen Pwned",
	auth: {
		function: "haveIBeenPwned",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "haveIBeenPwned" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "have-ibeen-pwned-custom-password-compromised-message",
				description:
					"Custom message to display when a password is compromised.",
				question:
					"[Have IBeen Pwned] What is the custom message for compromised passwords?",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "customPasswordCompromisedMessage",
					schema: z.coerce.string().optional(),
				},
			},
		],
	},
	authClient: null,
} as const satisfies PluginConfig;
