import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const emailOTPPluginConfig = {
	displayName: "Email OTP",
	auth: {
		function: "emailOTP",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "emailOTP" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "email-otp-send-verification-otp",
				description: "Function to send email verification",
				question: "[Email OTP] What is the send verification o t p?",
				defaultValue: `async ({ email, otp, type }, request) => {
 // Send email with OTP
}`,
				skipPrompt: true,
				isRequired: true,
				argument: {
					index: 0,
					isProperty: "sendVerificationOTP",
					schema: z.coerce.string(),
				},
			},
			{
				flag: "email-otp-otp-length",
				description: "Length of the OTP",
				question: "[Email OTP] What is the length of the OTP?",
				defaultValue: 6,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "otpLength",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "email-otp-expires-in",
				description: "Expiry time of the OTP in seconds default is 5 minutes",
				question: "[Email OTP] What is the expiry time of the OTP in seconds?",
				defaultValue: 300,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "expiresIn",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "email-otp-send-verification-on-sign-up",
				description: "Send email verification on sign-up",
				question: "[Email OTP] Would you like to send the OTP on sign-up?",
				defaultValue: false,
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "sendVerificationOnSignUp",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "email-otp-disable-sign-up",
				description:
					"A boolean value that determines whether to prevent automatic sign-up when the user is not registered.",
				question: "[Email OTP] Would you like to disable sign-up?",
				defaultValue: false,
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "disableSignUp",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "email-otp-allowed-attempts",
				description: "Allowed attempts for the OTP code",
				question: "[Email OTP] What is the allowed attempts for the OTP code?",
				defaultValue: 3,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "allowedAttempts",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "email-otp-store-otp",
				description:
					"Store the OTP in your database in a secure way Note: This will not affect the OTP sent to the user, it will only affect the OTP stored in your database",
				question: "[Email OTP] How would you like to store the OTP code?",
				defaultValue: "plain",
				skipPrompt: true,
				isSelectOptions: [
					{ value: "plain", label: "Plain" },
					{ value: "encrypted", label: "Encrypted" },
					{ value: "hashed", label: "Hashed" },
				],
				argument: {
					index: 0,
					isProperty: "storeOTP",
					schema: z.enum(["plain", "encrypted", "hashed"]).optional(),
				},
			},
			{
				flag: "email-otp-override-default-email-verification",
				description:
					"Override the default email verification to use email otp instead",
				question:
					"[Email OTP] Would you like to override the default email verification?",
				defaultValue: false,
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "overrideDefaultEmailVerification",
					schema: z.coerce.boolean().optional(),
				},
			},
		],
	},
	authClient: {
		function: "emailOTPClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "emailOTPClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
