import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const oneTapPluginConfig = {
  displayName: "One Tap",
  auth: {
    function: "oneTap",
    imports: [
      {
        path: "better-auth/plugins",
        imports: [createImport({ name: "oneTap" })],
        isNamedImport: false,
      },
    ],
    arguments: [
      {
        flag: "one-tap-disable-signup",
        description: "Disable the signup flow",
        question:
          "[One Tap] Would you like to disable the signup flow for one-tap?",
        defaultValue: false,
        skipPrompt: true,
        argument: {
          index: 0,
          isProperty: "disableSignup",
          schema: z.coerce.boolean().optional(),
        },
      },
      {
        flag: "one-tap-client-id",
        description:
          "Google Client ID If a client ID is provided in the social provider configuration, it will be used.",
        question: "[One Tap] What is the Google Client ID?",
        skipPrompt: true,
        argument: {
          index: 0,
          isProperty: "clientId",
          schema: z.coerce.string().optional(),
        },
      },
    ],
  },
  authClient: {
    function: "oneTapClient",
    imports: [
      {
        path: "better-auth/client/plugins",
        imports: [createImport({ name: "oneTapClient" })],
        isNamedImport: false,
      },
    ],
    arguments: [
      {
        flag: "one-tap-client-client-id",
        description: "Google client ID",
        question: "[One Tap Client] What is the Google Client ID?",
        defaultValue: "process.env.GOOGLE_ONE_TAP_CLIENT_ID",
        skipPrompt: true,
        isRequired: true,
        argument: {
          index: 0,
          isProperty: "clientId",
          schema: z.coerce.string(),
        },
      },
      {
        flag: "one-tap-client-auto-select",
        description: "Auto select the account if the user is already signed in",
        question:
          "[One Tap Client] Would you like to auto select the account if the user is already signed in?",
        defaultValue: false,
        skipPrompt: true,
        argument: {
          index: 0,
          isProperty: "autoSelect",
          schema: z.coerce.boolean().optional(),
        },
      },
      {
        flag: "one-tap-client-cancel-on-tap-outside",
        description: "Cancel the flow when the user taps outside the prompt",
        question:
          "[One Tap Client] Would you like to cancel the flow when the user taps outside the prompt?",
        defaultValue: true,
        skipPrompt: true,
        argument: {
          index: 0,
          isProperty: "cancelOnTapOutside",
          schema: z.coerce.boolean().optional(),
        },
      },
      {
        flag: "one-tap-client-ux-mode",
        description:
          "The mode to use for the Google One Tap flow popup: Use a popup window redirect: Redirect the user to the Google One Tap flow",
        question:
          "[One Tap Client] What is the UX mode for the Google One Tap flow?",
        defaultValue: "popup",
        skipPrompt: true,
        isSelectOptions: [
          { value: "popup", label: "Popup" },
          { value: "redirect", label: "Redirect" },
        ],
        argument: {
          index: 0,
          isProperty: "uxMode",
          schema: z.enum(["popup", "redirect"]).optional(),
        },
      },
      {
        flag: "one-tap-client-context",
        description:
          "The context to use for the Google One Tap flow. See https://developers.google.com/identity/gsi/web/reference/js-reference",
        question:
          "[One Tap Client] What is the context for the Google One Tap flow?",
        defaultValue: "signin",
        skipPrompt: true,
        isSelectOptions: [
          { value: "signin", label: "Signin" },
          { value: "signup", label: "Signup" },
          { value: "use", label: "Use" },
        ],
        argument: {
          index: 0,
          isProperty: "context",
          schema: z.enum(["signin", "signup", "use"]).optional(),
        },
      },
      {
        flag: "one-tap-client-prompt-options",
        description:
          "Configuration options for the prompt and exponential backoff behavior.",
        skipPrompt: true,
        isNestedObject: [
          {
            flag: "one-tap-client-prompt-options-base-delay",
            description:
              "Base delay (in milliseconds) for exponential backoff.",
            question:
              "[One Tap Client] What is the base delay for the Google One Tap flow?",
            defaultValue: 1000,
            skipPrompt: true,
            isNumber: true,
            argument: {
              index: 0,
              isProperty: "baseDelay",
              schema: z.coerce.number().optional(),
            },
          },
          {
            flag: "one-tap-client-prompt-options-max-attempts",
            description:
              "Maximum number of prompt attempts before calling onPromptNotification.",
            question:
              "[One Tap Client] What is the maximum number of prompt attempts before calling onPromptNotification?",
            defaultValue: 5,
            skipPrompt: true,
            isNumber: true,
            argument: {
              index: 0,
              isProperty: "maxAttempts",
              schema: z.coerce.number().optional(),
            },
          },
        ],
        argument: {
          index: 0,
          isProperty: "promptOptions",
        },
      },
    ],
  },
} as const satisfies PluginConfig;
