import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const usernamePluginConfig = {
	displayName: "Username",
	auth: {
		function: "username",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "username" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "username-min-username-length",
				description: "The minimum length of the username",
				question: "[Username] What is the min username length?",
				defaultValue: 3,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "minUsernameLength",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "username-max-username-length",
				description: "The maximum length of the username",
				question: "[Username] What is the max username length?",
				defaultValue: 30,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "maxUsernameLength",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "username-validation-order",
				description: "The order of validation",
				question: "[Username] What is the validation order?",
				skipPrompt: true,
				isNestedObject: [
					{
						flag: "username-validation-order-username",
						description: "The order of username validation",
						question: "[Username] What is the order of username validation?",
						defaultValue: "pre-normalization",
						skipPrompt: true,
						isSelectOptions: [
							{ value: "pre-normalization", label: "Pre-Normalization" },
							{ value: "post-normalization", label: "Post-Normalization" },
						],
						argument: {
							index: 0,
							isProperty: "username",
							schema: z.coerce.string().optional(),
						},
					},
					{
						flag: "username-validation-order-display-username",
						description: "The order of display username validation",
						question:
							"[Username] What is the order of display username validation?",
						defaultValue: "pre-normalization",
						skipPrompt: true,
						isSelectOptions: [
							{ value: "pre-normalization", label: "Pre-Normalization" },
							{ value: "post-normalization", label: "Post-Normalization" },
						],
						argument: {
							index: 0,
							isProperty: "displayUsername",
							schema: z.coerce.string().optional(),
						},
					},
				],
				argument: {
					index: 0,
					isProperty: "validationOrder",
				},
			},
		],
	},
	authClient: {
		function: "usernameClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "usernameClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
