import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const oneTimeTokenPluginConfig = {
	displayName: "One Time Token",
	auth: {
		function: "oneTimeToken",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "oneTimeToken" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "one-time-token-expires-in",
				description: "Expires in minutes",
				question:
					"[One Time Token] What is the one-time-token expiration time in minutes?",
				defaultValue: 3,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "expiresIn",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "one-time-token-disable-client-request",
				description: "Only allow server initiated requests",
				question:
					"[One Time Token] Should the one-time-token be only allowed to be generated by the server?",
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "disableClientRequest",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "one-time-token-store-token",
				description:
					"This option allows you to configure how the token is stored in your database. Note: This will not affect the token that's sent, it will only affect the token stored in your database.",
				question: "[One Time Token] How should tokens be stored?",
				defaultValue: "plain",
				skipPrompt: true,
				isSelectOptions: [
					{ value: "plain", label: "Plain" },
					{ value: "hashed", label: "Hashed" },
				],
				argument: {
					index: 0,
					isProperty: "storeToken",
					schema: z.enum(["plain", "hashed"]).optional(),
				},
			},
		],
	},
	authClient: {
		function: "oneTimeTokenClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "oneTimeTokenClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
