import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const organizationPluginConfig = {
	displayName: "Organization",
	auth: {
		function: "organization",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "organization" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "organization-allow-user-to-create-organization",
				description:
					"Configure whether new users are able to create new organizations. You can also pass a function that returns a boolean.",
				question: "[Organization] Are users allowed to create organizations?",
				defaultValue: true,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "allowUserToCreateOrganization",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "organization-organization-limit",
				description:
					"The maximum number of organizations a user can create. You can also pass a function that returns a boolean",
				question:
					"[Organization] What is the maximum number of organizations a user can create?",
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "organizationLimit",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "organization-creator-role",
				description:
					"The role that is assigned to the creator of the organization.",
				question:
					"[Organization] What is the role that is assigned to the creator of the organization?",
				defaultValue: "owner",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "creatorRole",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "organization-membership-limit",
				description:
					"The maximum number of members allowed in an organization.",
				question:
					"[Organization] What is the maximum number of members allowed in an organization?",
				defaultValue: 100,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "membershipLimit",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "organization-teams",
				description: "Support for team.",
				skipPrompt: true,
				isNestedObject: [
					{
						flag: "organization-teams-enabled",
						description: "Enable team features.",
						question:
							"[Organization] Would you like to support teams in organizations?",
						skipPrompt: false,
						isRequired: true,
						isConformation: true,
						argument: {
							index: 0,
							isProperty: "enabled",
							schema: z.coerce.boolean(),
						},
					},
					{
						flag: "organization-teams-maximum-teams",
						description:
							"Maximum number of teams an organization can have. You can pass a number or a function that returns a number.",
						question:
							"[Organization] What is the maximum number of teams an organization can have?",
						skipPrompt: true,
						isNumber: true,
						argument: {
							index: 0,
							isProperty: "maximumTeams",
							schema: z.coerce.number().optional(),
						},
					},
					{
						flag: "organization-teams-maximum-members-per-team",
						description:
							"The maximum number of members per team. if `undefined`, there is no limit.",
						question:
							"[Organization] What is the maximum number of members per team?",
						skipPrompt: true,
						isNumber: true,
						argument: {
							index: 0,
							isProperty: "maximumMembersPerTeam",
							schema: z.coerce.number().optional(),
						},
					},
					{
						flag: "organization-teams-allow-removing-all-teams",
						description:
							"By default, if an organization does only have one team, they'll not be able to remove it. You can disable this behavior by setting this to `false.",
						question: "[Organization] Allow removing all teams?",
						defaultValue: false,
						skipPrompt: true,
						isConformation: true,
						argument: {
							index: 0,
							isProperty: "allowRemovingAllTeams",
							schema: z.coerce.boolean().optional(),
						},
					},
				],
				argument: {
					index: 0,
					isProperty: "teams",
				},
			},
			{
				flag: "organization-invitation-expires-in",
				description: "The expiration time for the invitation link. In hours.",
				question:
					"[Organization] What is the expiration time for the invitation link in hours?",
				defaultValue: 48,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "invitationExpiresIn",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "organization-invitation-limit",
				description: "The maximum invitation a user can send.",
				question:
					"[Organization] What is the maximum number of invitations a user can send?",
				defaultValue: 100,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "invitationLimit",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "organization-cancel-pending-invitations-on-re-invite",
				description: "Cancel pending invitations on re-invite.",
				question: "[Organization] Cancel pending invitations on re-invite?",
				defaultValue: false,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "cancelPendingInvitationsOnReInvite",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "organization-require-email-verification-on-invitation",
				description:
					"Require email verification on accepting or rejecting an invitation",
				question:
					"[Organization] Require email verification on accepting or rejecting an invitation?",
				defaultValue: false,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "requireEmailVerificationOnInvitation",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "organization-disable-organization-deletion",
				description: "Disable organization deletion",
				question: "[Organization] Disable organization deletion?",
				defaultValue: false,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "disableOrganizationDeletion",
					schema: z.coerce.boolean().optional(),
				},
			},
		],
	},
	authClient: {
		function: "organizationClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "organizationClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
