import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const bearerPluginConfig = {
	displayName: "Bearer",
	auth: {
		function: "bearer",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "bearer" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "bearer-require-signature",
				description:
					"If true, only signed tokens will be converted to session cookies",
				question:
					"[Bearer] Would you like to require signature for bearer tokens?",
				defaultValue: false,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "requireSignature",
					schema: z.coerce.boolean().optional(),
				},
			},
		],
	},
	authClient: null,
} as const satisfies PluginConfig;
