import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const captchaPluginConfig = {
	displayName: "Captcha",
	auth: {
		function: "captcha",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "captcha" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "captcha-provider",
				description: "The captcha provider you wish to use.",
				question: "[Captcha] Which CAPTCHA provider do you want to use?",
				skipPrompt: false,
				isRequired: true,
				isSelectOptions: [
					{ value: "google-recaptcha", label: "Google-Recaptcha" },
					{ value: "cloudflare-turnstile", label: "Cloudflare-Turnstile" },
					{ value: "hcaptcha", label: "Hcaptcha" },
					{ value: "captchafox", label: "Captchafox" },
				],
				argument: {
					index: 0,
					isProperty: "provider",
					schema: z.enum([
						"google-recaptcha",
						"cloudflare-turnstile",
						"hcaptcha",
						"captchafox",
					]),
				},
			},
		],
	},
	authClient: null,
} as const satisfies PluginConfig;
