import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const ssoPluginConfig = {
	displayName: "Sso",
	auth: {
		function: "sso",
		imports: [
			{
				path: "@better-auth/sso",
				imports: [createImport({ name: "sso" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "sso-default-override-user-info",
				description: "Override user info with the provider info.",
				question:
					"[Sso] Would you like to override user info with the provider info?",
				defaultValue: false,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "defaultOverrideUserInfo",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "sso-disable-implicit-sign-up",
				description:
					"Disable implicit sign up for new users. When set to true for the provider, sign-in need to be called with with requestSignUp as true to create new users.",
				question:
					"[Sso] Would you like to disable implicit sign up for new users?",
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "disableImplicitSignUp",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "sso-providers-limit",
				description:
					"Configure the maximum number of SSO providers a user can register. You can also pass a function that returns a number. Set to 0 to disable SSO provider registration.",
				question:
					"[Sso] What is the maximum number of SSO providers a user can register?",
				defaultValue: 10,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "providersLimit",
					schema: z.coerce.number().optional(),
				},
			},
		],
	},
	authClient: {
		function: "ssoClient",
		imports: [
			{
				path: "@better-auth/sso/client",
				imports: [createImport({ name: "ssoClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
