import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const oidcProviderPluginConfig = {
	displayName: "Oidc Provider",
	auth: {
		function: "oidcProvider",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "oidcProvider" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "oidc-provider-access-token-expires-in",
				description:
					"The amount of time in seconds that the access token is valid for. By default it is 3600 seconds (1 hour) - Recommended by the OIDC spec",
				question:
					"[Oidc Provider] What is the amount of time in seconds that the access token is valid for?",
				defaultValue: 3600,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "accessTokenExpiresIn",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "oidc-provider-allow-dynamic-client-registration",
				description: "Allow dynamic client registration.",
				question:
					"[Oidc Provider] Would you like to allow dynamic client registration?",
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "allowDynamicClientRegistration",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "oidc-provider-refresh-token-expires-in",
				description:
					"The amount of time in seconds that the refresh token is valid for. By default it is 604800 seconds (7 days) - Recommended by the OIDC spec",
				question:
					"[Oidc Provider] What is the amount of time in seconds that the refresh token is valid for?",
				defaultValue: 604800,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "refreshTokenExpiresIn",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "oidc-provider-code-expires-in",
				description:
					"The amount of time in seconds that the authorization code is valid for. By default it is 600 seconds (10 minutes) - Recommended by the OIDC spec",
				question:
					"[Oidc Provider] What is the amount of time in seconds that the authorization code is valid for?",
				defaultValue: 600,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "codeExpiresIn",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "oidc-provider-scopes",
				description: "The scopes that the client is allowed to request.",
				question:
					"[Oidc Provider] What are the scopes that the client is allowed to request?",
				defaultValue: '["openid", "profile", "email", "offline_access"]',
				skipPrompt: true,
				cliTransform: (value) => {
					if (typeof value === "string") {
						try {
							const parsed = JSON.parse(value);
							if (Array.isArray(parsed)) {
								return parsed;
							}
						} catch {
							return value
								.split(",")
								.map((v) => v.trim())
								.filter((v) => v.length > 0);
						}
					}
					if (Array.isArray(value)) {
						return value;
					}
					return value;
				},
				argument: {
					index: 0,
					isProperty: "scopes",
					schema: z.coerce.string().array().optional(),
				},
			},
			{
				flag: "oidc-provider-default-scope",
				description:
					"The default scope to use if the client does not provide one.",
				question:
					"[Oidc Provider] What is the default scope to use if the client does not provide one?",
				defaultValue: "openid",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "defaultScope",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "oidc-provider-consent-page",
				description:
					"A URL to the consent page where the user will be redirected if the client requests consent. After the user consents, they should be redirected by the client to the `redirect_uri` with the authorization code. When the server redirects the user to the consent page, it will include the following query parameters: - `consent_code` - The consent code to identify the authorization request. - `client_id` - The ID of the client. - `scope` - The requested scopes. Once the user consents, you need to call the `/oauth2/consent` endpoint with `accept: true` and optionally the `consent_code` (if using URL parameter flow) to complete the authorization. This will return the client to the `redirect_uri` with the authorization code.",
				question: "[Oidc Provider] What is the URL to the consent page?",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "consentPage",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "oidc-provider-login-page",
				description:
					"The URL to the login page. This is used if the client requests the `login` prompt.",
				question: "[Oidc Provider] What is the URL to the login page?",
				defaultValue: "/login",
				skipPrompt: true,
				isRequired: true,
				argument: {
					index: 0,
					isProperty: "loginPage",
					schema: z.coerce.string(),
				},
			},
			{
				flag: "oidc-provider-require-pkce",
				description:
					"Whether to require PKCE (proof key code exchange) or not According to OAuth2.1 spec this should be required. But in any case if you want to disable this you can use this options.",
				question:
					"[Oidc Provider] Would you like to require PKCE (proof key code exchange)?",
				defaultValue: true,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "requirePKCE",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "oidc-provider-allow-plain-code-challenge-method",
				description: "Allow plain to be used as a code challenge method.",
				question:
					"[Oidc Provider] Would you like to allow plain to be used as a code challenge method?",
				defaultValue: true,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "allowPlainCodeChallengeMethod",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "oidc-provider-store-client-secret",
				description:
					'Store the client secret in your database in a secure way Note: This will not affect the client secret sent to the user, it will only affect the client secret stored in your database - "hashed" - The client secret is hashed using the `hash` function. - "plain" - The client secret is stored in the database in plain text. - "encrypted" - The client secret is encrypted using the `encrypt` function. - { hash: (clientSecret: string) => Promise<string> } - A function that hashes the client secret. - { encrypt: (clientSecret: string) => Promise<string>, decrypt: (clientSecret: string) => Promise<string> } - A function that encrypts and decrypts the client secret.',
				question:
					"[Oidc Provider] What is the method to store the client secret?",
				defaultValue: "plain",
				skipPrompt: true,
				isSelectOptions: [
					{ value: "hashed", label: "Hashed" },
					{ value: "plain", label: "Plain" },
					{ value: "encrypted", label: "Encrypted" },
				],
				argument: {
					index: 0,
					isProperty: "storeClientSecret",
					schema: z.enum(["hashed", "plain", "encrypted"]).optional(),
				},
			},
			{
				flag: "oidc-provider-use-jwtplugin",
				description: "Whether to use the JWT plugin to sign the ID token.",
				question:
					"[Oidc Provider] Would you like to use the JWT plugin to sign the ID token?",
				defaultValue: false,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "useJWTPlugin",
					schema: z.coerce.boolean().optional(),
				},
			},
		],
	},
	authClient: {
		function: "oidcProviderClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "oidcProviderClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
