import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const multiSessionPluginConfig = {
	displayName: "Multi Session",
	auth: {
		function: "multiSession",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "multiSession" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "multi-session-maximum-sessions",
				description: "The maximum number of sessions a user can have at a time",
				question:
					"[Multi Session] What is the maximum number of sessions a user can have at a time?",
				defaultValue: 5,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "maximumSessions",
					schema: z.coerce.number().optional(),
				},
			},
		],
	},
	authClient: {
		function: "multiSessionClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "multiSessionClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
