import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const jwtPluginConfig = {
	displayName: "Jwt",
	auth: {
		function: "jwt",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "jwt" })],
				isNamedImport: false,
			},
		],
	},
	authClient: null,
} as const satisfies PluginConfig;
