import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const deviceAuthorizationPluginConfig = {
	displayName: "Device Authorization",
	auth: {
		function: "deviceAuthorization",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "deviceAuthorization" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "device-authorization-expires-in",
				description:
					"Time in seconds until the device code expires. Use formats like '30m', '5s', '1h', etc.",
				question: "[Device Authorization] When should device codes expire?",
				defaultValue: "30m",
				skipPrompt: true,
				isRequired: true,
				argument: {
					index: 0,
					isProperty: "expiresIn",
					schema: z.coerce.string(),
				},
			},
			{
				flag: "device-authorization-interval",
				description:
					"Time in seconds between polling attempts. Use formats like '30m', '5s', '1h', etc.",
				question: "[Device Authorization] What is the polling interval?",
				defaultValue: "5s",
				skipPrompt: true,
				isRequired: true,
				argument: {
					index: 0,
					isProperty: "interval",
					schema: z.coerce.string(),
				},
			},
			{
				flag: "device-authorization-device-code-length",
				description:
					"Length of the device code to be generated. Default is 40 characters.",
				question:
					"[Device Authorization] What is the length of the device code?",
				defaultValue: 40,
				skipPrompt: true,
				isRequired: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "deviceCodeLength",
					schema: z.coerce.number(),
				},
			},
			{
				flag: "device-authorization-user-code-length",
				description:
					"Length of the user code to be generated. Default is 8 characters.",
				question: "[Device Authorization] What is the length of the user code?",
				defaultValue: 8,
				skipPrompt: true,
				isRequired: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "userCodeLength",
					schema: z.coerce.number(),
				},
			},
		],
	},
	authClient: {
		function: "deviceAuthorizationClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "deviceAuthorizationClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
