import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const apiKeyPluginConfig = {
	displayName: "Api Key",
	auth: {
		function: "apiKey",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "apiKey" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "api-key-api-key-headers",
				description: "The header name to check for API key",
				question: "[Api Key] What is the header name to check for API key?",
				defaultValue: "x-api-key",
				skipPrompt: true,
				cliTransform: (value) => {
					if (typeof value === "string") {
						try {
							const parsed = JSON.parse(value);
							if (Array.isArray(parsed)) {
								return parsed;
							}
						} catch {
							return value
								.split(",")
								.map((v) => v.trim())
								.filter((v) => v.length > 0);
						}
					}
					if (Array.isArray(value)) {
						return value;
					}
					return value;
				},
				argument: {
					index: 0,
					isProperty: "apiKeyHeaders",
					schema: z.coerce.string().array().optional(),
				},
			},
			{
				flag: "api-key-starting-characters-config",
				description:
					"The configuration for storing the starting characters of the API key in the database. Useful if you want to display the starting characters of an API key in the UI.",
				skipPrompt: true,
				isNestedObject: [
					{
						flag: "api-key-starting-characters-config-should-store",
						description:
							"Whether to store the starting characters in the database. If false, we will set `start` to `null`.",
						question:
							"[Api Key] Whether to store the starting characters in the database?",
						defaultValue: true,
						skipPrompt: true,
						argument: {
							index: 0,
							isProperty: "shouldStore",
							schema: z.coerce.boolean().optional(),
						},
					},
					{
						flag: "api-key-starting-characters-config-characters-length",
						description:
							"The length of the starting characters to store in the database. This includes the prefix length.",
						question:
							"[Api Key] What is the length of the starting characters to store in the database?",
						defaultValue: 6,
						skipPrompt: true,
						isNumber: true,
						argument: {
							index: 0,
							isProperty: "charactersLength",
							schema: z.coerce.number().optional(),
						},
					},
				],
				argument: {
					index: 0,
					isProperty: "startingCharactersConfig",
				},
			},
			{
				flag: "api-key-default-key-length",
				description:
					"The length of the API key. Longer is better. Default is 64. (Doesn't include the prefix length)",
				question: "[Api Key] What is the length of the API key?",
				defaultValue: 64,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "defaultKeyLength",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "api-key-default-prefix",
				description:
					"The prefix of the API key. Note: We recommend you append an underscore to the prefix to make the prefix more identifiable. (eg `hello_`)",
				question: "[Api Key] What is the prefix of the API key?",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "defaultPrefix",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "api-key-maximum-prefix-length",
				description: "The maximum length of the prefix.",
				question: "[Api Key] What is the maximum length of the prefix?",
				defaultValue: 32,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "maximumPrefixLength",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "api-key-require-name",
				description: "Whether to require a name for the API key.",
				question: "[Api Key] Whether to require a name for the API key?",
				defaultValue: false,
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "requireName",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "api-key-minimum-prefix-length",
				description: "The minimum length of the prefix.",
				question: "[Api Key] What is the minimum length of the prefix?",
				defaultValue: 1,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "minimumPrefixLength",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "api-key-maximum-name-length",
				description: "The maximum length of the name.",
				question: "[Api Key] What is the maximum length of the name?",
				defaultValue: 32,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "maximumNameLength",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "api-key-minimum-name-length",
				description: "The minimum length of the name.",
				question: "[Api Key] What is the minimum length of the name?",
				defaultValue: 1,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "minimumNameLength",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "api-key-enable-metadata",
				description: "Whether to enable metadata for an API key.",
				question: "[Api Key] Whether to enable metadata for an API key?",
				defaultValue: false,
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "enableMetadata",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "api-key-key-expiration",
				description: "Customize the key expiration.",
				skipPrompt: true,
				isNestedObject: [
					{
						flag: "api-key-key-expiration-default-expires-in",
						description:
							"The default expires time in milliseconds. If `null`, then there will be no expiration time.",
						question:
							"[Api Key] What is the default expires time in milliseconds?",
						defaultValue: "null",
						skipPrompt: true,
						isNumber: true,
						argument: {
							index: 0,
							isProperty: "defaultExpiresIn",
							schema: z.coerce.number().optional(),
						},
					},
					{
						flag: "api-key-key-expiration-disable-custom-expires-time",
						description:
							"Whether to disable the expires time passed from the client. If `true`, the expires time will be based on the default values.",
						question:
							"[Api Key] Whether to disable the expires time passed from the client?",
						defaultValue: false,
						skipPrompt: true,
						argument: {
							index: 0,
							isProperty: "disableCustomExpiresTime",
							schema: z.coerce.boolean().optional(),
						},
					},
					{
						flag: "api-key-key-expiration-min-expires-in",
						description:
							"The minimum expiresIn value allowed to be set from the client. in days.",
						question:
							"[Api Key] What is the minimum expiresIn value allowed to be set from the client?",
						defaultValue: 1,
						skipPrompt: true,
						isNumber: true,
						argument: {
							index: 0,
							isProperty: "minExpiresIn",
							schema: z.coerce.number().optional(),
						},
					},
					{
						flag: "api-key-key-expiration-max-expires-in",
						description:
							"The maximum expiresIn value allowed to be set from the client. in days.",
						question:
							"[Api Key] What is the maximum expiresIn value allowed to be set from the client?",
						defaultValue: 365,
						skipPrompt: true,
						isNumber: true,
						argument: {
							index: 0,
							isProperty: "maxExpiresIn",
							schema: z.coerce.number().optional(),
						},
					},
				],
				argument: {
					index: 0,
					isProperty: "keyExpiration",
				},
			},
			{
				flag: "api-key-rate-limit",
				description: "Default rate limiting options.",
				skipPrompt: true,
				isNestedObject: [
					{
						flag: "api-key-rate-limit-enabled",
						description: "Whether to enable rate limiting.",
						question: "[Api Key] Whether to enable rate limiting?",
						defaultValue: true,
						skipPrompt: true,
						argument: {
							index: 0,
							isProperty: "enabled",
							schema: z.coerce.boolean().optional(),
						},
					},
					{
						flag: "api-key-rate-limit-time-window",
						description:
							"The duration in milliseconds where each request is counted. Once the `maxRequests` is reached, the request will be rejected until the `timeWindow` has passed, at which point the `timeWindow` will be reset.",
						question:
							"[Api Key] What is the duration in milliseconds where each request is counted?",
						defaultValue: "1000 * 60 * 60 * 24 // 1 day",
						skipPrompt: true,
						isNumber: true,
						argument: {
							index: 0,
							isProperty: "timeWindow",
							schema: z.coerce.number().optional(),
						},
					},
					{
						flag: "api-key-rate-limit-max-requests",
						description:
							"Maximum amount of requests allowed within a window Once the `maxRequests` is reached, the request will be rejected until the `timeWindow` has passed, at which point the `timeWindow` will be reset.",
						question:
							"[Api Key] What is the maximum amount of requests allowed within a window?",
						defaultValue: "10 // 10 requests per day",
						skipPrompt: true,
						isNumber: true,
						argument: {
							index: 0,
							isProperty: "maxRequests",
							schema: z.coerce.number().optional(),
						},
					},
				],
				argument: {
					index: 0,
					isProperty: "rateLimit",
				},
			},
		],
	},
	authClient: {
		function: "apiKeyClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "apiKeyClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
