import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const lastLoginMethodPluginConfig = {
	displayName: "Last Login Method",
	auth: {
		function: "lastLoginMethod",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "lastLoginMethod" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "last-login-method-cookie-name",
				description: "Name of the cookie to store the last login method",
				question:
					"[Last Login Method] What is the cookie name for last login method?",
				defaultValue: "better-auth.last_used_login_method",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "cookieName",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "last-login-method-max-age",
				description:
					"Cookie expiration time in seconds. By default it's 2592000 seconds (30 days)",
				question:
					"[Last Login Method] What is the max age in seconds before the cookie expires?",
				defaultValue: 2592000,
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "maxAge",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "last-login-method-store-in-database",
				description:
					"Store the last login method in the database. This will create a new field in the user table.",
				question:
					"[Last Login Method] Should the last login method be stored in the database?",
				defaultValue: false,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "storeInDatabase",
					schema: z.coerce.boolean().optional(),
				},
			},
		],
	},
	authClient: {
		function: "lastLoginMethodClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "lastLoginMethodClient" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "last-login-method-client-cookie-name",
				description: "Name of the cookie to read the last login method from.",
				question:
					"[Last Login Method Client] What is the cookie name for last login method?",
				defaultValue: "better-auth.last_used_login_method",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "cookieName",
					schema: z.coerce.string().optional(),
				},
			},
		],
	},
} as const satisfies PluginConfig;
