import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const mcpPluginConfig = {
	displayName: "Mcp",
	auth: {
		function: "mcp",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "mcp" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "mcp-login-page",
				description: "The login page URL",
				question: "[Mcp] What is the login page URL?",
				defaultValue: "/login",
				skipPrompt: true,
				isRequired: true,
				argument: {
					index: 0,
					isProperty: "loginPage",
					schema: z.coerce.string(),
				},
			},
		],
	},
	authClient: null,
} as const satisfies PluginConfig;
