import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const adminPluginConfig = {
	displayName: "Admin",
	auth: {
		function: "admin",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "admin" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "admin-default-role",
				description: "The default role for a user.",
				question: "[Admin] What is the default role?",
				defaultValue: "user",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "defaultRole",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "admin-admin-roles",
				description:
					"Roles that are considered admin roles. Any user role that isn't in this list, even if they have the permission, will not be considered an admin.",
				question: "[Admin] What is the admin roles?",
				defaultValue: '["admin"]',
				skipPrompt: false,
				cliTransform: (value) => {
					if (typeof value === "string") {
						try {
							const parsed = JSON.parse(value);
							if (Array.isArray(parsed)) {
								return parsed;
							}
						} catch {
							return value
								.split(",")
								.map((v) => v.trim())
								.filter((v) => v.length > 0);
						}
					}
					if (Array.isArray(value)) {
						return value;
					}
					return value;
				},
				argument: {
					index: 0,
					isProperty: "adminRoles",
					schema: z.coerce.string().array().optional(),
				},
			},
		],
	},
	authClient: {
		function: "adminClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "adminClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
