import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const openAPIPluginConfig = {
	displayName: "Open API",
	auth: {
		function: "openAPI",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "openAPI" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "open-api-path",
				description:
					"The path to the OpenAPI reference page keep in mind that this path will be appended to the base URL `/api/auth` path by default, so if you set this to `/reference`, the full path will be `/api/auth/reference`",
				question: "[Open API] What is the path to the OpenAPI reference page?",
				defaultValue: "/reference",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "path",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "open-api-disable-default-reference",
				description:
					"Disable the default reference page that is generated by Scalar",
				question: "[Open API] Should the default reference page be disabled?",
				defaultValue: false,
				skipPrompt: true,
				isConformation: true,
				argument: {
					index: 0,
					isProperty: "disableDefaultReference",
					schema: z.coerce.boolean().optional(),
				},
			},
			{
				flag: "open-api-theme",
				description: "Theme of the OpenAPI reference page.",
				question: "[Open API] What is the theme of the OpenAPI reference page?",
				defaultValue: "default",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "theme",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "open-api-nonce",
				description:
					"A 'nonce' string to be attached to inline scripts for Content Security Policy (CSP) compliance.",
				question:
					"[Open API] What is the nonce string to be attached to inline scripts for Content Security Policy (CSP) compliance?",
				defaultValue: "undefined",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "nonce",
					schema: z.coerce.string().optional(),
				},
			},
		],
	},
	authClient: null,
} as const satisfies PluginConfig;
