import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const oauthProxyPluginConfig = {
	displayName: "Oauth Proxy",
	auth: {
		function: "oauthProxy",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "oauthProxy" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "oauth-proxy-current-url",
				description:
					'The current URL of the application. The plugin will attempt to infer the current URL from your environment by checking the base URL from popular hosting providers, from the request URL if invoked by a client, or as a fallback, from the `baseURL` in your auth config. If the URL is not inferred correctly, you can provide a value here."',
				question: "[Oauth Proxy] What is the current URL of the application?",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "currentURL",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "oauth-proxy-production-url",
				description:
					"If a request in a production url it won't be proxied. default to `BETTER_AUTH_URL`",
				question:
					"[Oauth Proxy] What is the production URL of the application?",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "productionURL",
					schema: z.coerce.string().optional(),
				},
			},
		],
	},
	authClient: {
		function: "oauthProxyClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "oauthProxyClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
