import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const magicLinkPluginConfig = {
  displayName: "Magic Link",
  auth: {
    function: "magicLink",
    imports: [
      {
        path: "better-auth/plugins",
        imports: [createImport({ name: "magicLink" })],
        isNamedImport: false,
      },
    ],
    arguments: [
      {
        flag: "magic-link-expires-in",
        description:
          "Time in seconds until the magic link expires. Default is (60 * 5) 5 minutes",
        question:
          "[Magic Link] What is the expiration time for the magic link in seconds?",
        defaultValue: 300,
        skipPrompt: true,
        isNumber: true,
        argument: {
          index: 0,
          isProperty: "expiresIn",
          schema: z.coerce.number().optional(),
        },
      },
      {
        flag: "magic-link-rate-limit",
        description:
          "Rate limit configuration. Default window is 60 seconds and max is 5 requests.",
        skipPrompt: true,
        isNestedObject: [
          {
            flag: "magic-link-rate-limit-window",
            description: "Window in seconds. Default is 60 seconds.",
            question: "[Magic Link] What is the window in seconds?",
            defaultValue: 60,
            skipPrompt: true,
            isNumber: true,
            argument: {
              index: 0,
              isProperty: "window",
              schema: z.coerce.number(),
            },
          },
          {
            flag: "magic-link-rate-limit-max",
            description: "Max requests. Default is 5 requests.",
            question: "[Magic Link] What is the max requests?",
            defaultValue: 5,
            skipPrompt: true,
            isNumber: true,
            argument: {
              index: 0,
              isProperty: "max",
              schema: z.coerce.number(),
            },
          },
        ],
        argument: {
          index: 0,
          isProperty: "rateLimit",
        },
      },
      {
        flag: "magic-link-store-token",
        description:
          "This option allows you to configure how the token is stored in your database. Note: This will not affect the token that's sent, it will only affect the token stored in your database.",
        question: "[Magic Link] How would you like to store the token?",
        defaultValue: "plain",
        skipPrompt: true,
        isSelectOptions: [
          { value: "plain", label: "Plain" },
          { value: "hashed", label: "Hashed" },
        ],
        argument: {
          index: 0,
          isProperty: "storeToken",
          schema: z.enum(["plain", "hashed"]).optional(),
        },
      },
    ],
  },
  authClient: {
    function: "magicLinkClient",
    imports: [
      {
        path: "better-auth/client/plugins",
        imports: [createImport({ name: "magicLinkClient" })],
        isNamedImport: false,
      },
    ],
  },
} as const satisfies PluginConfig;
