import * as z from "zod/v4";
import { createImport } from "../utility/imports";
import type { PluginConfig } from "./plugins-index.config";

// This file is automatically generated during build by a script called 'generate-plugin-config.ts'
// Read more about the script at /packages/cli/scripts/README.md

export const adminPluginConfig = {
	displayName: "Admin",
	auth: {
		function: "admin",
		imports: [
			{
				path: "better-auth/plugins",
				imports: [createImport({ name: "admin" })],
				isNamedImport: false,
			},
		],
		arguments: [
			{
				flag: "admin-default-role",
				description: "The default role for a user.",
				question: "[Admin] What is the default role?",
				defaultValue: "user",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "defaultRole",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "admin-admin-roles",
				description:
					"Roles that are considered admin roles. Any user role that isn't in this list, even if they have the permission, will not be considered an admin.",
				question: "[Admin] What is the admin roles?",
				defaultValue: '["admin"]',
				skipPrompt: false,
				cliTransform: (value) => {
					if (typeof value === "string") {
						try {
							const parsed = JSON.parse(value);
							if (Array.isArray(parsed)) {
								return parsed;
							}
						} catch {
							return value
								.split(",")
								.map((v) => v.trim())
								.filter((v) => v.length > 0);
						}
					}
					if (Array.isArray(value)) {
						return value;
					}
					return value;
				},
				argument: {
					index: 0,
					isProperty: "adminRoles",
					schema: z.coerce.string().array().optional(),
				},
			},
			{
				flag: "admin-default-ban-reason",
				description: "A default ban reason By default, no reason is provided",
				question: "[Admin] What is the default ban reason?",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "defaultBanReason",
					schema: z.coerce.string().optional(),
				},
			},
			{
				flag: "admin-default-ban-expires-in",
				description:
					"Number of seconds until the ban expires By default, the ban never expires",
				question: "[Admin] When does the ban expire by default?",
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "defaultBanExpiresIn",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "admin-impersonation-session-duration",
				description:
					"Duration of the impersonation session in seconds By default, the impersonation session lasts 1 hour",
				question:
					"[Admin] How long does the impersonation session last by default?",
				skipPrompt: true,
				isNumber: true,
				argument: {
					index: 0,
					isProperty: "impersonationSessionDuration",
					schema: z.coerce.number().optional(),
				},
			},
			{
				flag: "admin-admin-user-ids",
				description:
					"List of user ids that should have admin access If this is set, the `adminRole` option is ignored",
				question:
					"[Admin] What are the user ids that should have hard-coded admin access?",
				skipPrompt: true,
				cliTransform: (value) => {
					if (typeof value === "string") {
						try {
							const parsed = JSON.parse(value);
							if (Array.isArray(parsed)) {
								return parsed;
							}
						} catch {
							return value
								.split(",")
								.map((v) => v.trim())
								.filter((v) => v.length > 0);
						}
					}
					if (Array.isArray(value)) {
						return value;
					}
					return value;
				},
				argument: {
					index: 0,
					isProperty: "adminUserIds",
					schema: z.coerce.string().array().optional(),
				},
			},
			{
				flag: "admin-banned-user-message",
				description:
					'Message to show when a user is banned By default, the message is "You have been banned from this application"',
				question: "[Admin] What is the message to show when a user is banned?",
				skipPrompt: true,
				argument: {
					index: 0,
					isProperty: "bannedUserMessage",
					schema: z.coerce.string().optional(),
				},
			},
		],
	},
	authClient: {
		function: "adminClient",
		imports: [
			{
				path: "better-auth/client/plugins",
				imports: [createImport({ name: "adminClient" })],
				isNamedImport: false,
			},
		],
	},
} as const satisfies PluginConfig;
