import type { BindingContext } from "samlify/types/src/entity";
import type { FlowResult } from "samlify/types/src/flow";
import { createIdP, createSP } from "../routes/helpers";
import { saml } from "../samlify";
import type { SAMLAssertionExtract, SAMLConfig } from "../types";
import { normalizePem } from "../utils";

/**
 * Result of building an SP-initiated AuthnRequest (HTTP-Redirect binding).
 * Returned by {@link SAMLExecutor.createLoginRequest}.
 */
export interface SAMLLoginRequestResult {
	/**
	 * Full browser redirect URL (IdP SSO endpoint + SAMLRequest query params).
	 * Same shape as samlify `createLoginRequest(...).context`.
	 */
	redirectUrl: string;
	/**
	 * AuthnRequest ID. Better Auth stores this for InResponseTo correlation
	 * in the verification table (or secondary storage).
	 */
	id: string;
}

/**
 * Result of parsing and cryptographically validating a SAML Response.
 * Better Auth keeps ownership of domain lookup, InResponseTo consumption,
 * assertion replay storage, user provisioning, and session cookies.
 */
export interface SAMLParseLoginResponseResult {
	/** Assertion extract (nameID, attributes, conditions, etc.) */
	extract: SAMLAssertionExtract & {
		attributes?: Record<string, string | string[] | undefined>;
	};
	/**
	 * Decrypted (if needed) SAML response/assertion XML used for binding
	 * validation and assertion-id extraction.
	 */
	samlContent: string;
	/** SP entity ID used for audience checks. */
	entityId: string;
	/** ACS URL(s) used for recipient / destination checks. */
	assertionConsumerServiceUrl?: string | string[];
	/** IdP entity ID used for replay / issuer records. */
	idpEntityId: string;
	/**
	 * When true, the executor already validated signature algorithms and
	 * Better Auth skips local algorithm checks that require a full FlowResult.
	 * Local default executor sets this after running the same checks path
	 * via returning enough of the samlify parse result.
	 */
	signatureValidated: boolean;
	/**
	 * Optional raw samlify FlowResult for local algorithm validation.
	 * Remote executors typically omit this and set signatureValidated=true.
	 */
	rawParsedResponse?: FlowResult;
}

export interface SAMLCreateLoginRequestInput {
	providerId: string;
	samlConfig: SAMLConfig;
	baseURL: string;
	/** RelayState value already generated by Better Auth (signed state cookie path). */
	relayState: string;
}

export interface SAMLParseLoginResponseInput {
	providerId: string;
	samlConfig: SAMLConfig;
	baseURL: string;
	/** Whitespace-normalized SAMLResponse (base64). */
	SAMLResponse: string;
	RelayState?: string;
	clockSkew?: number;
}

/**
 * Pluggable SAML crypto executor (transport-agnostic).
 *
 * Better Auth keeps sessions, domain → provider discovery, InResponseTo /
 * replay storage, user provisioning, and cookies. The executor only performs
 * heavy SAML crypto (AuthnRequest build + Response parse/verify).
 *
 * Implementations may run in-process, over HTTP, RPC, a queue worker, WASM,
 * or any other host — Better Auth only requires these two async functions.
 *
 * Custom executors that verify signatures must set
 * `signatureValidated: true` on {@link SAMLParseLoginResponseResult}.
 * Alternatively return `rawParsedResponse` so Better Auth can run its local
 * algorithm checks (used by {@link createLocalSAMLExecutor}).
 *
 * @example Any remote transport
 * ```ts
 * sso({
 *   saml: {
 *     executor: {
 *       createLoginRequest: (input) => myBridge.rpc("createLoginRequest", input),
 *       parseLoginResponse: (input) => myBridge.rpc("parseLoginResponse", input),
 *     },
 *   },
 * })
 * ```
 *
 * Reference crypto for a Node-capable host:
 * ```ts
 * import { createLocalSAMLExecutor } from "@better-auth/sso";
 * const executor = createLocalSAMLExecutor();
 * ```
 */
export interface SAMLExecutor {
	createLoginRequest(
		input: SAMLCreateLoginRequestInput,
	): Promise<SAMLLoginRequestResult>;
	parseLoginResponse(
		input: SAMLParseLoginResponseInput,
	): Promise<SAMLParseLoginResponseResult>;
}

/**
 * Default in-process executor using samlify (same behavior as pre-executor SSO).
 * Safe to import from a Node Lambda that only does SAML crypto.
 */
export function createLocalSAMLExecutor(): SAMLExecutor {
	return {
		async createLoginRequest(input) {
			const { samlConfig, baseURL, providerId, relayState } = input;
			let metadata = samlConfig.spMetadata.metadata;

			if (!metadata) {
				metadata =
					saml
						.SPMetadata({
							entityID: samlConfig.spMetadata?.entityID || samlConfig.issuer,
							assertionConsumerService: [
								{
									Binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
									Location:
										samlConfig.callbackUrl ||
										`${baseURL}/sso/saml2/sp/acs/${providerId}`,
								},
							],
							wantMessageSigned: samlConfig.wantAssertionsSigned || false,
							authnRequestsSigned: samlConfig.authnRequestsSigned || false,
							nameIDFormat: samlConfig.identifierFormat
								? [samlConfig.identifierFormat]
								: undefined,
						})
						.getMetadata() || "";
			}

			const sp = saml.ServiceProvider({
				metadata: metadata,
				allowCreate: true,
				privateKey: normalizePem(
					samlConfig.spMetadata?.privateKey || samlConfig.privateKey,
				),
				privateKeyPass: samlConfig.spMetadata?.privateKeyPass,
				relayState,
			});

			const idpData = samlConfig.idpMetadata;
			const idp = !idpData?.metadata
				? saml.IdentityProvider({
						entityID: idpData?.entityID || samlConfig.issuer,
						singleSignOnService: idpData?.singleSignOnService || [
							{
								Binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
								Location: samlConfig.entryPoint,
							},
						],
						signingCert: idpData?.cert || samlConfig.cert,
						wantAuthnRequestsSigned: samlConfig.authnRequestsSigned || false,
						isAssertionEncrypted: idpData?.isAssertionEncrypted || false,
						encPrivateKey: normalizePem(idpData?.encPrivateKey),
						encPrivateKeyPass: idpData?.encPrivateKeyPass,
					})
				: saml.IdentityProvider({
						metadata: idpData.metadata,
						privateKey: normalizePem(idpData.privateKey),
						privateKeyPass: idpData.privateKeyPass,
						isAssertionEncrypted: idpData.isAssertionEncrypted,
						encPrivateKey: normalizePem(idpData.encPrivateKey),
						encPrivateKeyPass: idpData.encPrivateKeyPass,
					});

			const loginRequest = sp.createLoginRequest(
				idp,
				"redirect",
			) as BindingContext & {
				entityEndpoint: string;
				type: string;
				id: string;
				context: string;
			};

			if (!loginRequest?.context || !loginRequest.id) {
				throw new Error("Invalid SAML AuthnRequest: missing context or id");
			}

			return {
				redirectUrl: loginRequest.context,
				id: loginRequest.id,
			};
		},

		async parseLoginResponse(input) {
			const {
				samlConfig,
				baseURL,
				providerId,
				SAMLResponse,
				RelayState,
				clockSkew,
			} = input;
			const sp = createSP(samlConfig, baseURL, providerId, { clockSkew });
			const idp = createIdP(samlConfig);

			const parsedResponse = await sp.parseLoginResponse(idp, "post", {
				body: {
					SAMLResponse,
					RelayState: RelayState || undefined,
				},
			});

			if (!parsedResponse?.extract) {
				throw new Error("Invalid SAML response structure");
			}

			const assertionConsumerServiceUrl =
				sp.entityMeta.getAssertionConsumerService(
					"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
				);

			return {
				extract:
					parsedResponse.extract as SAMLParseLoginResponseResult["extract"],
				samlContent: parsedResponse.samlContent,
				entityId: sp.entityMeta.getEntityID(),
				assertionConsumerServiceUrl,
				idpEntityId: idp.entityMeta.getEntityID(),
				// Local path still runs BA algorithm validation on rawParsedResponse.
				signatureValidated: false,
				rawParsedResponse: parsedResponse,
			};
		},
	};
}

/** Resolve the active executor: custom remote or in-process samlify. */
export function resolveSAMLExecutor(
	executor: SAMLExecutor | undefined,
): SAMLExecutor {
	return executor ?? createLocalSAMLExecutor();
}
