import type { BindingContext } from "samlify/types/src/entity";
import type { FlowResult } from "samlify/types/src/flow";
import { createIdP, createSP } from "../routes/helpers";
import { saml } from "../samlify";
import type { SAMLAssertionExtract, SAMLConfig } from "../types";
import { normalizePem } from "../utils";
import type {
	AlgorithmValidationOptions,
	SAMLCryptoReport,
} from "./algorithms";
import { createSAMLCryptoReport } from "./algorithms";

/**
 * Result of building an SP-initiated AuthnRequest (HTTP-Redirect binding).
 */
export interface SAMLLoginRequestResult {
	/**
	 * Full browser redirect URL (IdP SSO endpoint + SAMLRequest query params).
	 * Same shape as samlify `createLoginRequest(...).context`.
	 */
	redirectUrl: string;
	/**
	 * AuthnRequest ID. Better Auth stores this for InResponseTo correlation.
	 */
	id: string;
}

/**
 * Result of parsing a SAML Response.
 *
 * Better Auth owns domain discovery, InResponseTo / replay storage, user
 * provisioning, and sessions. The executor only returns verified claims + a
 * structured {@link SAMLCryptoReport} so host policy stays uniform.
 */
export interface SAMLParseLoginResponseResult {
	/** Assertion extract (nameID, attributes, conditions, etc.) */
	extract: SAMLAssertionExtract & {
		attributes?: Record<string, string | string[] | undefined>;
	};
	/**
	 * Assertion XML used for binding validation and assertion-id extraction.
	 * Must be **decrypted** (no EncryptedAssertion) so replay protection works.
	 */
	samlContent: string;
	/** SP entity ID (informational; audience checks use local config). */
	entityId: string;
	/** ACS URL(s) from the SP used during parse (informational). */
	assertionConsumerServiceUrl?: string | string[];
	/** IdP entity ID used for replay / issuer records when available. */
	idpEntityId: string;
	/**
	 * Crypto verification report — the library contract for operator algorithm
	 * policy. Use {@link createSAMLCryptoReport} to build this.
	 */
	crypto: SAMLCryptoReport;
	/**
	 * @internal Local samlify path only: original parse result (may still
	 * contain EncryptedAssertion) for the binding decrypt helper.
	 */
	rawParsedResponse?: FlowResult;
}

export interface SAMLCreateLoginRequestInput {
	providerId: string;
	samlConfig: SAMLConfig;
	baseURL: string;
	/** RelayState value already generated by Better Auth. */
	relayState: string;
}

export interface SAMLParseLoginResponseInput {
	providerId: string;
	samlConfig: SAMLConfig;
	baseURL: string;
	/** Whitespace-normalized SAMLResponse (base64). */
	SAMLResponse: string;
	RelayState?: string;
	clockSkew?: number;
	/**
	 * Operator algorithm policy (`SSOOptions.saml.algorithms`).
	 * Optional for executors that also enforce policy remotely; Better Auth
	 * always re-applies policy via {@link enforceSAMLCryptoPolicy} on the host.
	 */
	algorithms?: AlgorithmValidationOptions;
}

/**
 * Pluggable SAML crypto executor (transport-agnostic).
 *
 * Implement these two methods with any backend (in-process, HTTP, RPC, WASM…).
 * Better Auth keeps sessions, domain discovery, and security policy.
 *
 * @example
 * ```ts
 * sso({
 *   saml: {
 *     executor: {
 *       createLoginRequest: (input) => bridge.rpc("createLoginRequest", input),
 *       parseLoginResponse: (input) => bridge.rpc("parseLoginResponse", input),
 *     },
 *   },
 * })
 * ```
 *
 * On a Node-capable host, reuse default crypto:
 * ```ts
 * import { createLocalSAMLExecutor } from "@better-auth/sso";
 * const executor = createLocalSAMLExecutor();
 * ```
 */
export interface SAMLExecutor {
	createLoginRequest(
		input: SAMLCreateLoginRequestInput,
	): Promise<SAMLLoginRequestResult>;
	parseLoginResponse(
		input: SAMLParseLoginResponseInput,
	): Promise<SAMLParseLoginResponseResult>;
}

/**
 * Default in-process executor using samlify.
 * Safe to run on a Node host that only performs SAML crypto.
 */
export function createLocalSAMLExecutor(): SAMLExecutor {
	return {
		async createLoginRequest(input) {
			const { samlConfig, baseURL, providerId, relayState } = input;
			let metadata = samlConfig.spMetadata.metadata;

			if (!metadata) {
				metadata =
					saml
						.SPMetadata({
							entityID: samlConfig.spMetadata?.entityID || samlConfig.issuer,
							assertionConsumerService: [
								{
									Binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
									Location:
										samlConfig.callbackUrl ||
										`${baseURL}/sso/saml2/sp/acs/${providerId}`,
								},
							],
							wantMessageSigned: samlConfig.wantAssertionsSigned || false,
							authnRequestsSigned: samlConfig.authnRequestsSigned || false,
							nameIDFormat: samlConfig.identifierFormat
								? [samlConfig.identifierFormat]
								: undefined,
						})
						.getMetadata() || "";
			}

			const sp = saml.ServiceProvider({
				metadata: metadata,
				allowCreate: true,
				privateKey: normalizePem(
					samlConfig.spMetadata?.privateKey || samlConfig.privateKey,
				),
				privateKeyPass: samlConfig.spMetadata?.privateKeyPass,
				relayState,
			});

			const idpData = samlConfig.idpMetadata;
			const idp = !idpData?.metadata
				? saml.IdentityProvider({
						entityID: idpData?.entityID || samlConfig.issuer,
						singleSignOnService: idpData?.singleSignOnService || [
							{
								Binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
								Location: samlConfig.entryPoint,
							},
						],
						signingCert: idpData?.cert || samlConfig.cert,
						wantAuthnRequestsSigned: samlConfig.authnRequestsSigned || false,
						isAssertionEncrypted: idpData?.isAssertionEncrypted || false,
						encPrivateKey: normalizePem(idpData?.encPrivateKey),
						encPrivateKeyPass: idpData?.encPrivateKeyPass,
					})
				: saml.IdentityProvider({
						metadata: idpData.metadata,
						privateKey: normalizePem(idpData.privateKey),
						privateKeyPass: idpData.privateKeyPass,
						isAssertionEncrypted: idpData.isAssertionEncrypted,
						encPrivateKey: normalizePem(idpData.encPrivateKey),
						encPrivateKeyPass: idpData.encPrivateKeyPass,
					});

			const loginRequest = sp.createLoginRequest(
				idp,
				"redirect",
			) as BindingContext & {
				entityEndpoint: string;
				type: string;
				id: string;
				context: string;
			};

			if (!loginRequest?.context || !loginRequest.id) {
				throw new Error("Invalid SAML AuthnRequest: missing context or id");
			}

			return {
				redirectUrl: loginRequest.context,
				id: loginRequest.id,
			};
		},

		async parseLoginResponse(input) {
			const {
				samlConfig,
				baseURL,
				providerId,
				SAMLResponse,
				RelayState,
				clockSkew,
			} = input;
			const sp = createSP(samlConfig, baseURL, providerId, { clockSkew });
			const idp = createIdP(samlConfig);

			const parsedResponse = await sp.parseLoginResponse(idp, "post", {
				body: {
					SAMLResponse,
					RelayState: RelayState || undefined,
				},
			});

			if (!parsedResponse?.extract) {
				throw new Error("Invalid SAML response structure");
			}

			const assertionConsumerServiceUrl =
				sp.entityMeta.getAssertionConsumerService(
					"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
				);

			const sigAlg =
				typeof (parsedResponse as { sigAlg?: string | null }).sigAlg ===
				"string"
					? (parsedResponse as { sigAlg?: string | null }).sigAlg
					: null;

			// Capture encryption algorithms from the (possibly still encrypted)
			// samlify content before the host decrypts for binding checks.
			const crypto = createSAMLCryptoReport({
				signatureVerified: true,
				signatureAlgorithm: sigAlg,
				sourceXml: parsedResponse.samlContent,
			});

			return {
				extract:
					parsedResponse.extract as SAMLParseLoginResponseResult["extract"],
				samlContent: parsedResponse.samlContent,
				entityId: sp.entityMeta.getEntityID(),
				assertionConsumerServiceUrl,
				idpEntityId: idp.entityMeta.getEntityID(),
				crypto,
				rawParsedResponse: parsedResponse,
			};
		},
	};
}

/** Resolve the active executor: custom plug-in or in-process samlify. */
export function resolveSAMLExecutor(
	executor: SAMLExecutor | undefined,
): SAMLExecutor {
	return executor ?? createLocalSAMLExecutor();
}

export type { SAMLCryptoReport };
