import { defineConfig } from "tsdown";

export default defineConfig({
	dts: { build: true, incremental: true },
	format: ["esm"],
	entry: [
		"./src/index.ts",
		"./src/server.ts",
		"./src/db.ts",
		"./src/client.ts",
		"./src/better-auth.ts",
		"./src/plugins.ts",
		"./src/react.ts",
		"./src/social-providers.ts",
		"./src/init.ts",
	],
	clean: true,
	noExternal: ["better-auth", /@better-auth\/.*/, /better-auth\/.*/],
	external: [
		"prisma",
		"@prisma/client",
		"better-sqlite3",
		"react",
		"vue",
		"solid-js",
		"solid-js/store",
		"next/headers",
		"$app/environment",
		"vitest",
		"@vitest/runner",
		"@vitest/utils",
		"@vitest/expect",
		"@vitest/snapshot",
		"@vitest/spy",
		"chai",
		"mongodb",
		"drizzle-orm",
		"pathe",
		"std-env",
		"magic-string",
		"pretty-format",
		"p-limit",
		"tinyspy",
		"next/dist/compiled/@edge-runtime/cookies",
		"@tanstack/react-start",
		"@tanstack/start-server-core",
		"bson",
		"mongodb-connection-string-url",
		"@mongodb-js/saslprep",
		"kerberos",
		"@mongodb-js/zstd",
		"nanostores",
		"@aws-sdk/credential-providers",
		"mongodb-client-encryption",
		"@vue/runtime-dom",
		"@vue/runtime-core",
		"@vue/shared",
		"@vue/reactivity",
		"@vue/compiler-dom",
		"@vue/compiler-core",
		"@babel/types",
		"@babel/parser",
		"punycode",
		"@sveltejs/kit",
		"svelte/compiler",
		"@sveltejs/vite-plugin-svelte",
		"csstype",
		"siwe",
		"@lynx-js/react",
	],
});
