export const AGENTS_ERROR_CODES = {
  UNAUTHORIZED: "AGENTS_UNAUTHORIZED",
  NAME_REQUIRED: "AGENTS_NAME_REQUIRED",
  ID_REQUIRED: "AGENTS_ID_REQUIRED",
  USER_ID_REQUIRED: "AGENTS_USER_ID_REQUIRED",
  AGENT_NOT_FOUND: "AGENTS_AGENT_NOT_FOUND",
  FORBIDDEN: "AGENTS_FORBIDDEN",
  ORGANIZATION_ID_REQUIRED: "AGENTS_ORGANIZATION_ID_REQUIRED",
  NOT_MEMBER_OF_ORGANIZATION: "AGENTS_NOT_MEMBER_OF_ORGANIZATION",
  FAILED_TO_UPDATE: "AGENTS_FAILED_TO_UPDATE",
  DATABASE_CONNECTION_NOT_AVAILABLE: "AGENTS_DATABASE_CONNECTION_NOT_AVAILABLE",
} as const

