name: Auto Label

on:
  pull_request_target:
    types: [opened, synchronize]

permissions: {}

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'better-auth'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          sync-labels: false
          dot: true
