name: Lint GitHub Actions

on:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
  push:
    branches:
      - main
      - next
      - "release/**"
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
    uses: better-auth/shared-workflows/.github/workflows/lint-github-actions.yml@08e5520e7a829b03bee1152913682b67d2ba44b1
