name: Release

on:
  push:
    branches:
      - v1.6.x
  workflow_dispatch:

permissions: {}

jobs:
  release:
    permissions:
      contents: read
      id-token: write
    uses: better-auth/better-auth/.github/workflows/release.yml@9ca15f3726275f31d86cbd0a8cf21fea64441634
    with:
      use_shared_tooling: true
    secrets:
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
