name: TypeScript Compilation Benchmark

on:
  push:
    branches: [ main, canary ]
  pull_request:
    branches: [ main, canary ]
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run TypeScript compilation benchmarks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Cache turbo build setup
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Run TypeScript compilation with trace
        working-directory: packages/better-auth
        run: |
          mkdir -p benchmark-results
          pnpm exec tsc -p tsconfig.json --generateTrace benchmark-results/trace

      - name: Extract benchmark metrics
        working-directory: packages/better-auth
        run: |
          node ../../scripts/extract-tsc-metrics.js benchmark-results/trace > benchmark-results/output.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: TypeScript Compilation Benchmark
          tool: 'customSmallerIsBetter'
          output-file-path: packages/better-auth/benchmark-results/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '120%'
          comment-on-alert: true
          fail-on-alert: false
          benchmark-data-dir-path: 'benchmarks/tsc'

      - name: Upload trace artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tsc-trace-${{ github.sha }}
          path: |
            packages/better-auth/benchmark-results/trace/
            packages/better-auth/benchmark-results/output.json
          retention-days: 30