name: Verify Changesets

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, edited]
    branches:
      - v1.6.x
  merge_group:

permissions: {}

jobs:
  verify:
    permissions:
      contents: read
      pull-requests: read
    uses: better-auth/better-auth/.github/workflows/verify-changesets.yml@0e02187ab45a903c66986fc5e28cddd37185147b
